# Generated by Django 4.2.4 on 2023-08-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='USA', max_length=30, verbose_name='Country'),
        ),
    ]
