# Generated by Django 4.2.4 on 2023-08-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='Unknown', max_length=155, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='Unknown', max_length=50, unique=True, verbose_name='phone number'),
        ),
    ]
