# Generated by Django 3.0.3 on 2020-10-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201007_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=5550)),
            ],
        ),
    ]
